name = "HEPExampleProject"
uuid = "f779019a-d216-4ac1-8c1a-8c09799cc4e6"
authors = ["Uwe Hernandez Acosta <u.hernandez@hzdr.de>"]
version = "0.0.1-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
