#/bin/bash

##  Must be run from same directory:
# ./make.sh && ./hepexample

set -e

julia -e 'exit(VERSION >= v"1.12" ? 0 : 1)' || (
	echo "ERROR: Need julia >= v1.12 for juliac support." >&2
	exit 1
)

# Binaries generated by juliac may segfault if JULIA_CPU_TARGET is set:
unset JULIA_CPU_TARGET

jlbindir=`julia -e 'println(dirname(Sys.BINDIR))'`

julia --project=. -e 'import Pkg; Pkg.instantiate()'

julia --project=. "$jlbindir/share/julia/juliac/juliac.jl" --experimental --trim=unsafe-warn --output-exe hepexample hepexample.jl
